In [1]:
import pickle
import numpy as np
import pandas as pd
# 指定.pkl文件的路径
# file_path = 'data/census13/original.pkl'
# file_path = 'data/census13/workload/base.pkl'
# file_path = 'data/census13/workload/base-original-label.pkl'
# file_path = 'data/census13/original.table.pkl'
file_path = 'data/census13/lstm/original_lstm-small_200_123.pkl'
# file_path = 'data/census13/lw/original_base_200_123.pkl'
# file_path = 'data/census13/workload/lstm-original-label.pkl'
# file_path = 'data/census13/workload/lstm-small-original-label.pkl'
# file_path = 'data/census13/workload/lstm-small.pkl'



# 打开文件并读取数据
with open(file_path, 'rb') as file:
    data = pickle.load(file)

In [2]:
data

{'train': ([array([0.04571885, 0.60000002, 0.60000002, 0.73333335, 0.86666667,
          0.71428573, 0.71428573, 0.        , 0.        , 0.        ,
          0.        ]),
   array([0.00264117, 0.33333334, 0.33333334, 0.        , 0.53333336,
          0.5       , 0.5       , 0.        , 0.        , 0.        ,
          0.        ]),
   array([0.00112608, 0.13333334, 0.13333334, 0.2       , 0.73333335,
          0.42857143, 0.42857143, 0.        , 0.        , 0.        ,
          0.        ]),
   array([1.84267639e-04, 4.00000006e-01, 4.00000006e-01, 0.00000000e+00,
          5.33333361e-01, 7.85714269e-01, 7.85714269e-01, 0.00000000e+00,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
   array([0.03804103, 1.        , 1.        , 0.33333334, 0.86666667,
          0.07142857, 0.07142857, 0.        , 0.        , 0.        ,
          0.        ]),
   array([0.04146022, 0.60000002, 0.60000002, 0.33333334, 1.        ,
          0.2857143 , 0.2857143 , 0.        , 0.        ,

In [17]:
data.data.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'sex', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country'],
      dtype='object')

In [10]:
data.columns["workclass"].vocab

array(['?', 'Federal-gov', 'Local-gov', 'Never-worked', 'Private',
       'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay'],
      dtype=object)

In [18]:
data.columns["workclass"].value_2_domain

{'?': 0.0,
 'Federal-gov': 0.125,
 'Local-gov': 0.25,
 'Never-worked': 0.375,
 'Private': 0.5,
 'Self-emp-inc': 0.625,
 'Self-emp-not-inc': 0.75,
 'State-gov': 0.875,
 'Without-pay': 1.0}

In [12]:
data.columns["age"].vocab

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90])

In [9]:
data.columns["age"].value_2_domain

{17: 0.0,
 18: 0.01369863,
 19: 0.02739726,
 20: 0.04109589,
 21: 0.05479452,
 22: 0.06849315,
 23: 0.08219178,
 24: 0.09589041,
 25: 0.10958904,
 26: 0.12328767,
 27: 0.1369863,
 28: 0.15068494,
 29: 0.16438356,
 30: 0.1780822,
 31: 0.19178082,
 32: 0.20547946,
 33: 0.21917808,
 34: 0.23287672,
 35: 0.24657534,
 36: 0.26027396,
 37: 0.2739726,
 38: 0.28767124,
 39: 0.30136988,
 40: 0.31506848,
 41: 0.32876712,
 42: 0.34246576,
 43: 0.3561644,
 44: 0.369863,
 45: 0.38356164,
 46: 0.39726028,
 47: 0.41095892,
 48: 0.42465752,
 49: 0.43835616,
 50: 0.4520548,
 51: 0.46575344,
 52: 0.47945204,
 53: 0.49315068,
 54: 0.5068493,
 55: 0.5205479,
 56: 0.53424656,
 57: 0.5479452,
 58: 0.56164384,
 59: 0.5753425,
 60: 0.5890411,
 61: 0.60273975,
 62: 0.6164383,
 63: 0.63013697,
 64: 0.6438356,
 65: 0.65753424,
 66: 0.6712329,
 67: 0.6849315,
 68: 0.69863015,
 69: 0.7123288,
 70: 0.72602737,
 71: 0.739726,
 72: 0.75342464,
 73: 0.7671233,
 74: 0.7808219,
 75: 0.79452056,
 76: 0.8082192,
 77: 0.82

In [2]:
vars(data)

{'dataset': 'census13',
 'version': 'original',
 'name': 'census13_original',
 'data':        age         workclass  education  education_num      marital_status  \
 0       39         State-gov  Bachelors             13       Never-married   
 1       50  Self-emp-not-inc  Bachelors             13  Married-civ-spouse   
 2       38           Private    HS-grad              9            Divorced   
 3       53           Private       11th              7  Married-civ-spouse   
 4       28           Private  Bachelors             13  Married-civ-spouse   
 ...    ...               ...        ...            ...                 ...   
 48837   39           Private  Bachelors             13            Divorced   
 48838   64                 ?    HS-grad              9             Widowed   
 48839   38           Private  Bachelors             13  Married-civ-spouse   
 48840   44           Private  Bachelors             13            Divorced   
 48841   35      Self-emp-inc  Bachelors     

In [2]:
data.columns["age"].normalize(39).item()

0.30136987566947937

In [11]:
data.columns["workclass"].normalize("Federal-gov").item()

0.125

In [43]:
for str_ in ['?', 'Federal-gov', 'Local-gov', 'Never-worked', 'Private',
       'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay']:
    print(data.columns["workclass"].normalize(str_).item())

0.0
0.125
0.25
0.375
0.5
0.625
0.75
0.875
1.0


In [9]:
col_name = "capital_gain"
col_list = np.sort(np.unique(data.data[col_name]))
for str_ in col_list:
    print(data.columns[col_name].normalize(str_).item())

0.0
0.0011400113580748439
0.004010040313005447
0.005940059199929237
0.009140091016888618
0.00991009920835495
0.010550105944275856
0.010860108770430088
0.011110111139714718
0.01151011511683464
0.011730117723345757
0.012640126049518585
0.014090141281485558
0.014240141957998276
0.014550145715475082
0.014710146933794022
0.015060150995850563
0.016390163451433182
0.01731017231941223
0.01797018013894558
0.0183101836591959
0.01848018541932106
0.020090200006961823
0.020360203459858894
0.02050020545721054
0.020620206370949745
0.021050211042165756
0.02174021676182747
0.02176021784543991
0.02202022075653076
0.022280223667621613
0.022900229319930077
0.023290233686566353
0.023460235446691513
0.023540236055850983
0.023870239034295082
0.024070240557193756
0.024140240624547005
0.024630246683955193
0.025380253791809082
0.025800257921218872
0.025970259681344032
0.026350263506174088
0.02653026580810547
0.0282902829349041
0.028850289061665535
0.029070289805531502
0.029360294342041016
0.029610296711325645
0

In [8]:
col_list

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90])

In [38]:
vs = np.sort(np.unique(data.data["workclass"]))
vs

array(['?', 'Federal-gov', 'Local-gov', 'Never-worked', 'Private',
       'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay'],
      dtype=object)

In [28]:
data.data

age         workclass  education  education_num      marital_status  \
0       39         State-gov  Bachelors             13       Never-married   
1       50  Self-emp-not-inc  Bachelors             13  Married-civ-spouse   
2       38           Private    HS-grad              9            Divorced   
3       53           Private       11th              7  Married-civ-spouse   
4       28           Private  Bachelors             13  Married-civ-spouse   
...    ...               ...        ...            ...                 ...   
48837   39           Private  Bachelors             13            Divorced   
48838   64                 ?    HS-grad              9             Widowed   
48839   38           Private  Bachelors             13  Married-civ-spouse   
48840   44           Private  Bachelors             13            Divorced   
48841   35      Self-emp-inc  Bachelors             13  Married-civ-spouse   

              occupation    relationship                race     sex  \
0           Adm-clerical   Not-in-family               White    Male   
1        Exec-managerial         Husband               White    Male   
2      Handlers-cleaners   Not-in-family               White    Male   
3      Handlers-cleaners         Husband               Black    Male   
4         Prof-specialty            Wife               Black  Female   
...                  ...             ...                 ...     ...   
48837     Prof-specialty   Not-in-family               White  Female   
48838                  ?  Other-relative               Black    Male   
48839     Prof-specialty         Husband               White    Male   
48840       Adm-clerical       Own-child  Asian-Pac-Islander    Male   
48841    Exec-managerial         Husband               White    Male   

       capital_gain  capital_loss  hours_per_week native_country  
0              2174             0              40  United-States  
1                 0             0              13  United-States  
2                 0             0              40  United-States  
3                 0             0              40  United-States  
4                 0             0              40           Cuba  
...             ...           ...             ...            ...  
48837             0             0              36  United-States  
48838             0             0              40  United-States  
48839             0             0              50  United-States  
48840          5455             0              40  United-States  
48841             0             0              60  United-States  

[48842 rows x 13 columns]

In [23]:
data_nor = data.normalize()

In [26]:
data_nor

age  workclass  education  education_num  marital_status  \
0      0.301370      0.875   0.600000       0.800000        0.666667   
1      0.452055      0.750   0.600000       0.800000        0.333333   
2      0.287671      0.500   0.733333       0.533333        0.000000   
3      0.493151      0.500   0.066667       0.400000        0.333333   
4      0.150685      0.500   0.600000       0.800000        0.333333   
...         ...        ...        ...            ...             ...   
48837  0.301370      0.500   0.600000       0.800000        0.000000   
48838  0.643836      0.000   0.733333       0.533333        1.000000   
48839  0.287671      0.500   0.600000       0.800000        0.333333   
48840  0.369863      0.500   0.600000       0.800000        0.000000   
48841  0.246575      0.625   0.600000       0.800000        0.333333   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
0        0.071429           0.2  1.00  1.0      0.021740           0.0   
1        0.285714           0.0  1.00  1.0      0.000000           0.0   
2        0.428571           0.2  1.00  1.0      0.000000           0.0   
3        0.428571           0.0  0.50  1.0      0.000000           0.0   
4        0.714286           1.0  0.50  0.0      0.000000           0.0   
...           ...           ...   ...  ...           ...           ...   
48837    0.714286           0.2  1.00  0.0      0.000000           0.0   
48838    0.000000           0.4  0.50  1.0      0.000000           0.0   
48839    0.714286           0.0  1.00  1.0      0.000000           0.0   
48840    0.071429           0.6  0.25  1.0      0.054551           0.0   
48841    0.285714           0.0  1.00  1.0      0.000000           0.0   

       hours_per_week  native_country  
0            0.397959        0.951219  
1            0.122449        0.951219  
2            0.397959        0.951219  
3            0.397959        0.951219  
4            0.397959        0.121951  
...               ...             ...  
48837        0.357143        0.951219  
48838        0.397959        0.951219  
48839        0.500000        0.951219  
48840        0.397959        0.951219  
48841        0.602041        0.951219  

[48842 rows x 13 columns]

In [13]:
data.get_minmax_dict()

{0: (17, 90),
 1: ('?', 'Without-pay'),
 2: ('10th', 'Some-college'),
 3: (1, 16),
 4: ('Divorced', 'Widowed'),
 5: ('?', 'Transport-moving'),
 6: ('Husband', 'Wife'),
 7: ('Amer-Indian-Eskimo', 'White'),
 8: ('Female', 'Male'),
 9: (0, 99999),
 10: (0, 4356),
 11: (1, 99),
 12: ('?', 'Yugoslavia')}

In [2]:
len(data["train"])

50000

In [3]:
data["train"][:10]

[Query(predicates=OrderedDict([('age', None), ('workclass', None), ('education', None), ('education_num', None), ('marital_status', ('=', 'Divorced')), ('occupation', None), ('relationship', ('=', 'Not-in-family')), ('race', ('=', 'White')), ('sex', ('=', 'Female')), ('capital_gain', None), ('capital_loss', None), ('hours_per_week', None), ('native_country', None)]), ncols=4),
 Query(predicates=OrderedDict([('age', None), ('workclass', None), ('education', None), ('education_num', None), ('marital_status', ('=', 'Never-married')), ('occupation', None), ('relationship', ('=', 'Own-child')), ('race', ('=', 'White')), ('sex', ('=', 'Male')), ('capital_gain', None), ('capital_loss', None), ('hours_per_week', None), ('native_country', None)]), ncols=4),
 Query(predicates=OrderedDict([('age', None), ('workclass', None), ('education', None), ('education_num', None), ('marital_status', ('=', 'Married-civ-spouse')), ('occupation', None), ('relationship', ('=', 'Husband')), ('race', ('=', 'White

In [ ]:
def discretize(self, data):
    """Transforms data values into integers using a Column's vocabulary"""

    # pd.Categorical() does not allow categories be passed in an array
    # containing np.nan.  It makes it a special case to return code -1
    # for NaN values.
    if self.has_nan:
        bin_ids = pd.Categorical(data, categories=self.vocab[1:]).codes
        # Since nan/nat bin_id is supposed to be 0 but pandas returns -1, just
        # add 1 to everybody
        bin_ids = bin_ids + 1
    else:
        # This column has no nan or nat values.
        bin_ids = pd.Categorical(data, categories=self.vocab).codes

    bin_ids = bin_ids.astype(np.int32, copy=False)
    assert (bin_ids >= 0).all(), (self, data, bin_ids)
    return bin_ids

In [48]:
data.columns["workclass"].discretize(data.data['workclass'])

array([7, 6, 4, ..., 4, 4, 5], dtype=int32)

In [51]:

for str_ in ['?', 'Federal-gov', 'Local-gov', 'Never-worked', 'Private',
       'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay']:
    print(data.columns["workclass"].discretize(str_))
    print(type(data.columns["workclass"].discretize(str_)[0]))

[0]
<class 'numpy.int32'>
[1]
<class 'numpy.int32'>
[2]
<class 'numpy.int32'>
[3]
<class 'numpy.int32'>
[4]
<class 'numpy.int32'>
[5]
<class 'numpy.int32'>
[6]
<class 'numpy.int32'>
[7]
<class 'numpy.int32'>
[8]
<class 'numpy.int32'>


In [2]:
members = [attr for attr in vars(data) if not callable(getattr(data, attr))]
members

TypeError: vars() argument must have __dict__ attribute

In [3]:
'explain(analyze, format json) SELECT * FROM "census13_original" WHERE workclass = \'Private\''
SELECT * FROM census13_original WHERE workclass = 'Private';

TypeError: vars() argument must have __dict__ attribute

In [29]:
for keys in data.keys():
    print("type(data[keys]) ", type(data[keys]))
    print("len(data[keys])", len(data[keys]))
    for tu_ in data[keys]:
        print(keys, "len(tu_)", len(tu_))
        print(tu_[0])
    break

type(data[keys])  <class 'tuple'>
len(data[keys]) 3
train len(tu_) 100000
[   0.         1000.          500.          500.            0.
 1000.            0.         1000.          666.66668653  666.66668653
    0.         1000.          200.00000298  200.00000298    0.
 1000.         1000.         1000.            0.           93.03035587
    0.         1000.            0.         1000.          951.21949911
  951.21949911    9.17242751   12.14625045   13.61930296]
train len(tu_) 100000
11.38586240064146
train len(tu_) 100000
2675


In [16]:
import math

result = math.pow(10, 4.5)
print(result)

31622.776601683792


In [11]:
import torch

# 示例文本序列
text_sequence_1 = [
    torch.FloatTensor([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0]]),
    torch.FloatTensor([[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0]])
]

text_sequence_2 = [
    torch.FloatTensor([[4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0]]),
    torch.FloatTensor([[3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0]])
]

# 转换为 PyTorch FloatTensor
your_texts = [text_sequence_1, text_sequence_2]

# 输出
print(your_texts)


[[tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.]]), tensor([[ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.]])], [tensor([[ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.]]), tensor([[ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.]])]]


In [52]:
import numpy as np
import pandas as pd

my_list = [23, 45, 12, 34, 23, 34]

# 使用NumPy进行排序
sorted_array = np.sort(my_list)

# 使用Pandas创建DataFrame
df = pd.DataFrame(sorted_array, columns=['values'])

# 计算累计小于等于每个值的数量
df['count'] = df.groupby('values').cumcount() + 1

# 计算比例
df['ratio'] = df['count'] / len(df)

# 去重，获取每个唯一值对应的最终结果
result = df.drop_duplicates(subset='values', keep='last')[['values', 'count', 'ratio']].reset_index(drop=True)

print(result)


   values  count     ratio
0      12      1  0.166667
1      23      2  0.333333
2      34      2  0.333333
3      45      1  0.166667


In [30]:
import pandas as pd

# Your DataFrame
# data = {'col1': ["hello", "appple", "?", "chdis", "chdis"],
#         'col2': [1, 2, 2, 1, 1],
#         'col3': [3, 4, 5, 6, 6]}

# df = pd.DataFrame(data)

data = data

# Sort by 'col1' and 'col2' in ascending order
df_sorted = df.sort_values(by=['col1', 'col2']).reset_index(drop=True)

# Calculate cumulative count and ratio
count_df = df_sorted.groupby(df_sorted.columns.tolist()).cumcount() + 1
ratio_df = count_df / len(df_sorted)

# Add count and ratio columns to the original DataFrame
df['count'] = count_df
df['ratio'] = ratio_df

# Drop duplicates to get the final result
result = df.drop_duplicates().reset_index(drop=True)

print(result)


     col1  col2  col3  count  ratio
0   hello     1     3      1    0.2
1  appple     2     4      1    0.2
2       ?     2     5      1    0.2
3   chdis     1     6      2    0.4
4   chdis     1     6      1    0.2


In [25]:
import pandas as pd

df = pd.DataFrame(["hello", "appple", "?", "chdis"], columns=['col1'])

# Sort values in ascending order
df_sorted = df.sort_values(by='col1').reset_index(drop=True)

print(df_sorted)


     col1
0       ?
1  appple
2   chdis
3   hello


In [25]:
import pandas as pd

# Your DataFrame
# data = {'col1': ["hello", "appple", "?", "chdis", "chdis"],
#         'col2': [1, 2, 2, 1, 1],
#         'col3': [3, 4, 5, 6, 6]}

# df = pd.DataFrame(data)
# 从data中选择'capital_loss'和'hours_per_week'两列
selected_columns = ['capital_loss', 'hours_per_week']
selected_data = data.data[selected_columns]

# 将选择的数据转换为DataFrame
df = pd.DataFrame(selected_data)

# Sort by 'col1' and 'col2' in ascending order
df_sorted = df.sort_values(by=selected_columns).reset_index(drop=True)
type(df_sorted)



pandas.core.frame.DataFrame

In [28]:
# Count the occurrences of each unique row
row_counts = df_sorted.groupby(df_sorted.columns.tolist()).size().reset_index(name='count')

# Calculate the percentage of each row's occurrence in the total number of rows
row_counts['percentage'] = row_counts['count'] / len(df_sorted)
# Calculate the cumulative probability
row_counts['cumulative_probability'] = row_counts['percentage'].cumsum()

# Display the result
print(row_counts)


     capital_loss  hours_per_week  count  percentage  cumulative_probability
0               0               1     25    0.000512                0.000512
1               0               2     50    0.001024                0.001536
2               0               3     55    0.001126                0.002662
3               0               4     83    0.001699                0.004361
4               0               5     92    0.001884                0.006245
..            ...             ...    ...         ...                     ...
742          3770              40      2    0.000041                0.999877
743          3770              45      1    0.000020                0.999898
744          3900              40      2    0.000041                0.999939
745          4356              18      1    0.000020                0.999959
746          4356              40      2    0.000041                1.000000

[747 rows x 5 columns]


In [18]:
# Count the occurrences of each unique row
row_counts = df_sorted.groupby(df_sorted.columns.tolist()).size().reset_index(name='count')

# Calculate the percentage of each row's occurrence in the total number of rows
# row_counts['percentage'] = row_counts['count'] / len(df_sorted)
# Calculate the cumulative probability
row_counts['cumulative_probability'] =  (row_counts['count'] / len(df_sorted)).cumsum()

# Display the result
print(row_counts)


     capital_loss  hours_per_week  count  cumulative_probability
0               0               1     25                0.000512
1               0               2     50                0.001536
2               0               3     55                0.002662
3               0               4     83                0.004361
4               0               5     92                0.006245
..            ...             ...    ...                     ...
742          3770              40      2                0.999877
743          3770              45      1                0.999898
744          3900              40      2                0.999939
745          4356              18      1                0.999959
746          4356              40      2                1.000000

[747 rows x 4 columns]


In [27]:
# Count the occurrences of each unique row
row_counts = df_sorted.groupby(df_sorted.columns.tolist()).size().reset_index(name='count')

# Calculate the cumulative probability directly using cumsum
row_counts['cumulative_probability'] = row_counts['count'].cumsum() / len(df_sorted)

# Display the result
print(row_counts)


     capital_loss  hours_per_week  count  cumulative_probability
0               0               1     25                0.000512
1               0               2     50                0.001536
2               0               3     55                0.002662
3               0               4     83                0.004361
4               0               5     92                0.006245
..            ...             ...    ...                     ...
742          3770              40      2                0.999877
743          3770              45      1                0.999898
744          3900              40      2                0.999939
745          4356              18      1                0.999959
746          4356              40      2                1.000000

[747 rows x 4 columns]


In [23]:
# Calculate the cumulative probability directly using cumsum on the size
cumulative_probability = df_sorted.groupby(df_sorted.columns.tolist()).size().cumsum() / len(df_sorted)

# Create a DataFrame with the cumulative probability
result_df = pd.DataFrame({'cumulative_probability': cumulative_probability}).reset_index()

# Display the result
print(result_df)


     capital_loss  hours_per_week  cumulative_probability
0               0               1                0.000512
1               0               2                0.001536
2               0               3                0.002662
3               0               4                0.004361
4               0               5                0.006245
..            ...             ...                     ...
742          3770              40                0.999877
743          3770              45                0.999898
744          3900              40                0.999939
745          4356              18                0.999959
746          4356              40                1.000000

[747 rows x 3 columns]


In [21]:
# Calculate the cumulative probability directly using cumsum on the size
cumulative_probability = df_sorted.groupby(df_sorted.columns.tolist()).size().cumsum() / len(df_sorted)

In [22]:
cumulative_probability

capital_loss  hours_per_week
0             1                 0.000512
              2                 0.001536
              3                 0.002662
              4                 0.004361
              5                 0.006245
                                  ...   
3770          40                0.999877
              45                0.999898
3900          40                0.999939
4356          18                0.999959
              40                1.000000
Length: 747, dtype: float64

In [22]:
import pandas as pd
import numpy as np
np.sort(["hello", "appple", "?", "chdis"])

array(['?', 'appple', 'chdis', 'hello'], dtype='<U6')